//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuLongCRM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhuLongCRM.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÔNG VIỆC HÔM NAY.
        /// </summary>
        internal static string cong_viec_hom_nay {
            get {
                return ResourceManager.GetString("cong_viec_hom_nay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã bán.
        /// </summary>
        internal static string da_ban {
            get {
                return ResourceManager.GetString("da_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chuyển đổi.
        /// </summary>
        internal static string da_chuyen_doi {
            get {
                return ResourceManager.GetString("da_chuyen_doi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhận.
        /// </summary>
        internal static string da_nhan {
            get {
                return ResourceManager.GetString("da_nhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string dang_nhap {
            get {
                return ResourceManager.GetString("dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt cọc.
        /// </summary>
        internal static string dat_coc {
            get {
                return ResourceManager.GetString("dat_coc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string dong {
            get {
                return ResourceManager.GetString("dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ đăng nhập.
        /// </summary>
        internal static string ghi_nho_dang_nhap {
            get {
                return ResourceManager.GetString("ghi_nho_dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIAO DỊCH.
        /// </summary>
        internal static string giao_dich {
            get {
                return ResourceManager.GetString("giao_dich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giữ chỗ.
        /// </summary>
        internal static string giu_cho {
            get {
                return ResourceManager.GetString("giu_cho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOA HỒNG.
        /// </summary>
        internal static string hoa_hong {
            get {
                return ResourceManager.GetString("hoa_hong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay không có công việc.
        /// </summary>
        internal static string hom_nay_khong_co_cong_vec {
            get {
                return ResourceManager.GetString("hom_nay_khong_co_cong_vec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng.
        /// </summary>
        internal static string hop_dong {
            get {
                return ResourceManager.GetString("hop_dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string khach_hang {
            get {
                return ResourceManager.GetString("khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng mới.
        /// </summary>
        internal static string khach_hang_moi {
            get {
                return ResourceManager.GetString("khach_hang_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHÁCH HÀNG TIỀM NĂNG.
        /// </summary>
        internal static string khach_hang_tiem_nang {
            get {
                return ResourceManager.GetString("khach_hang_tiem_nang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không cập nhật được thông tin Imei.
        /// </summary>
        internal static string khong_cap_nhat_duoc_thong_tin_imei {
            get {
                return ResourceManager.GetString("khong_cap_nhat_duoc_thong_tin_imei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không chuyển đổi.
        /// </summary>
        internal static string khong_chuyen_doi {
            get {
                return ResourceManager.GetString("khong_chuyen_doi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin. Vui lòng thử lại.
        /// </summary>
        internal static string khong_tim_thay_thong_tin_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy user.
        /// </summary>
        internal static string khong_tim_thay_user {
            get {
                return ResourceManager.GetString("khong_tim_thay_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối đến Server..
        /// </summary>
        internal static string loi_ket_noi_dern_server {
            get {
                return ResourceManager.GetString("loi_ket_noi_dern_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string mat_khau {
            get {
                return ResourceManager.GetString("mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        internal static string mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        internal static string mat_khau_khong_duong_de_trong {
            get {
                return ResourceManager.GetString("mat_khau_khong_duong_de_trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không thể đăng nhập trên thiết bị này.
        /// </summary>
        internal static string tai_khoan_khong_the_dang_nhap_tren_thiet_bi_nay {
            get {
                return ResourceManager.GetString("tai_khoan_khong_the_dang_nhap_tren_thiet_bi_nay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string ten_dang_nhap {
            get {
                return ResourceManager.GetString("ten_dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không đúng.
        /// </summary>
        internal static string ten_dang_nhap_khong_dung {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được để trống.
        /// </summary>
        internal static string ten_dang_nhap_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        internal static string thoi_gian {
            get {
                return ResourceManager.GetString("thoi_gian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string thong_bao {
            get {
                return ResourceManager.GetString("thong_bao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string tong_tien {
            get {
                return ResourceManager.GetString("tong_tien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string trang_chu {
            get {
                return ResourceManager.GetString("trang_chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        internal static string xem_them {
            get {
                return ResourceManager.GetString("xem_them", resourceCulture);
            }
        }
    }
}
