//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuLongCRM.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PhuLongCRM.Resources.Language.en", typeof(Language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string dang_nhap {
            get {
                return ResourceManager.GetString("dang_nhap", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap {
            get {
                return ResourceManager.GetString("ten_dang_nhap", resourceCulture);
            }
        }
        
        internal static string mat_khau {
            get {
                return ResourceManager.GetString("mat_khau", resourceCulture);
            }
        }
        
        internal static string ghi_nho_dang_nhap {
            get {
                return ResourceManager.GetString("ghi_nho_dang_nhap", resourceCulture);
            }
        }
        
        internal static string trang_chu {
            get {
                return ResourceManager.GetString("trang_chu", resourceCulture);
            }
        }
        
        internal static string hoa_hong {
            get {
                return ResourceManager.GetString("hoa_hong", resourceCulture);
            }
        }
        
        internal static string tong_tien {
            get {
                return ResourceManager.GetString("tong_tien", resourceCulture);
            }
        }
        
        internal static string da_nhan {
            get {
                return ResourceManager.GetString("da_nhan", resourceCulture);
            }
        }
        
        internal static string giao_dich {
            get {
                return ResourceManager.GetString("giao_dich", resourceCulture);
            }
        }
        
        internal static string giu_cho {
            get {
                return ResourceManager.GetString("giu_cho", resourceCulture);
            }
        }
        
        internal static string dat_coc {
            get {
                return ResourceManager.GetString("dat_coc", resourceCulture);
            }
        }
        
        internal static string hop_dong {
            get {
                return ResourceManager.GetString("hop_dong", resourceCulture);
            }
        }
        
        internal static string da_ban {
            get {
                return ResourceManager.GetString("da_ban", resourceCulture);
            }
        }
        
        internal static string khach_hang_tiem_nang {
            get {
                return ResourceManager.GetString("khach_hang_tiem_nang", resourceCulture);
            }
        }
        
        internal static string khach_hang_moi {
            get {
                return ResourceManager.GetString("khach_hang_moi", resourceCulture);
            }
        }
        
        internal static string da_chuyen_doi {
            get {
                return ResourceManager.GetString("da_chuyen_doi", resourceCulture);
            }
        }
        
        internal static string khong_chuyen_doi {
            get {
                return ResourceManager.GetString("khong_chuyen_doi", resourceCulture);
            }
        }
        
        internal static string cong_viec_hom_nay {
            get {
                return ResourceManager.GetString("cong_viec_hom_nay", resourceCulture);
            }
        }
        
        internal static string xem_them {
            get {
                return ResourceManager.GetString("xem_them", resourceCulture);
            }
        }
        
        internal static string hom_nay_khong_co_cong_vec {
            get {
                return ResourceManager.GetString("hom_nay_khong_co_cong_vec", resourceCulture);
            }
        }
        
        internal static string khach_hang {
            get {
                return ResourceManager.GetString("khach_hang", resourceCulture);
            }
        }
        
        internal static string thoi_gian {
            get {
                return ResourceManager.GetString("thoi_gian", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_thong_tin_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_duong_de_trong {
            get {
                return ResourceManager.GetString("mat_khau_khong_duong_de_trong", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap_khong_dung {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_dung", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_khong_dung", resourceCulture);
            }
        }
        
        internal static string tai_khoan_khong_the_dang_nhap_tren_thiet_bi_nay {
            get {
                return ResourceManager.GetString("tai_khoan_khong_the_dang_nhap_tren_thiet_bi_nay", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_user {
            get {
                return ResourceManager.GetString("khong_tim_thay_user", resourceCulture);
            }
        }
        
        internal static string loi_ket_noi_dern_server {
            get {
                return ResourceManager.GetString("loi_ket_noi_dern_server", resourceCulture);
            }
        }
        
        internal static string thong_bao {
            get {
                return ResourceManager.GetString("thong_bao", resourceCulture);
            }
        }
        
        internal static string dong {
            get {
                return ResourceManager.GetString("dong", resourceCulture);
            }
        }
        
        internal static string khong_cap_nhat_duoc_thong_tin_imei {
            get {
                return ResourceManager.GetString("khong_cap_nhat_duoc_thong_tin_imei", resourceCulture);
            }
        }
    }
}
